pipeline {
    agent any
    stages {

        stage('testing pipeline'){
          steps{
		    echo 'Demo - 1'
                //
                sh 'touch from-jenkins/demo.txt'
                }
        }
